[package]
name = "geosbt"
version = "0.1.0"
authors = ["Sebastian Ehlert <ehlert@thch.uni-bonn.de>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"
ndarray = "0.12.1"
ndarray-linalg = { version = "0.10", features = ["openblas"] }
statrs = "0.10"
